// web/components/layout/index.tsx
import React, { FC } from 'react'
import { LayoutProps } from 'ssr-types-react'
import App from './App'

const Layout: FC<LayoutProps> = (props: LayoutProps) => {
  const { injectState } = props
  const { injectCss, injectScript } = props.staticList ?? {}

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="theme-color" content="#000000" />
        <title>Kova</title>
        {injectCss}
      </head>
      <body className="bg-white dark:bg-black text-white dark:text-black">
        <div id="app">
          <App>{props.children}</App>
        </div>
        {injectState}
        {injectScript}
      </body>
    </html>
  )
}

export default Layout

// web/components/layout/index.vue

<script lang="ts" setup>
import { computed } from "vue";

const siteTitle = computed(() => {
  return 'Kova'
})

</script>

<template>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="theme-color" content="#000000" />
    <title>{{ siteTitle }}</title>
    <slot name="viteClient" />
    <slot name="customeHeadScript" />
    <slot name="cssInject" />
  </head>
  <body>
    <div id="app">
      <slot name="children" />
    </div>
    <slot name="initialData" />
    <slot name="customeFooterScript" />
    <slot name="jsInject" />
  </body>
</html>
</template>
